<table border="0" cellpadding="2" style="border-collapse: collapse" bordercolor="#111111" width="100%" id="AutoNumber5">
      <tr>
        <td width="100%" valign="top">
	<table border="1" cellpadding="2" style="border-collapse: collapse; border-style: dotted; border-width: 1" bordercolor="#111111" width="100%" height="300" bgcolor="#006633">
          <tr>
          <td align="center" bgcolor="#FFFFFF">
<?php
include_once("charts/charts.php");
echo InsertChart("charts/charts.php","charts/charts_library","pangkat.php",575,383);
?>
 </td>
          </tr>
        </table>
        </td>
        
    </table>